version: '2'

services:

  bootstrap:
    image: holochain/holochain-proto:develop
    ports:
      - "3142:3142"
    command: bs

  holo-vault1:
    image: holochain/holochain-proto:develop
    ports:
      - "3141:3141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holo-vault"
    command: bash -c "cd /holo-vault; hcdev -agentID=lucy -bootstrapServer=bootstrap:3142 web 3141"

  holo-vault2:
    image: holochain/holochain-proto:develop
    ports:
      - "4141:4141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holo-vault"
    command: bash -c "cd /holo-vault; hcdev -agentID=phil -bootstrapServer=bootstrap:3142 web 4141"

  holo-vault3:
    image: holochain/holochain-proto:develop
    ports:
      - "5141:5141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holo-vault"
    command: bash -c "cd /holo-vault; hcdev -agentID=clarence -bootstrapServer=bootstrap:3142 web 5141"
